[versions]
kotlin = '1.8.21'
kotlin-logging = '3.+'
micronaut = '4.2.4'
micronaut-plugin = '4.2.1'
shadow = '8.1.1'
testcontainers-kafka = '1.17.6'
logback = '1.4.13'

[libraries]
kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }
kotlin-logging = { module = 'io.github.microutils:kotlin-logging', version.ref = 'kotlin-logging' }
logback = { module = 'ch.qos.logback:logback-classic', version.ref = 'logback' }
testcontainers-kafka = { module = 'org.testcontainers:kafka', version.ref = 'testcontainers-kafka' }

[plugins]
kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }
kotlin-allopen = { id = 'org.jetbrains.kotlin.plugin.allopen', version.ref = 'kotlin' }
kotlin-kapt = { id = 'org.jetbrains.kotlin.kapt', version.ref = 'kotlin' }
micronaut-application = { id = 'io.micronaut.application', version.ref = 'micronaut-plugin' }
micronaut-aot = { id = 'io.micronaut.aot', version.ref = 'micronaut-plugin' }
shadow = { id = 'com.github.johnrengelman.shadow', version.ref = 'shadow' }
